version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"
  #secrets-manager:
     # key: secret-id:json-key:version-stage:version-id
     # key: secret-id:json-key:version-stage:version-id
  #exported-variables:
     # - variable
     # - variable
  #git-credential-helper: yes
#batch:
  #fast-fail: true
  #build-list:
  #build-matrix:
  #build-graph:
phases:
  install:
    #If you use the Ubuntu standard image 2.0 or later, you must specify runtime-versions.
    #If you specify runtime-versions and use an image other than Ubuntu standard image 2.0, the build fails.
    #runtime-versions:
      # name: version
      # name: version
    commands:
       - echo "Install"
      # - command
  pre_build:
    commands:
       - echo "pre_build"
      # - command
  build:
    commands:
      - apt update && apt -y dist-upgrade
      - apt-get install gcc binutils bzip2 flex python3 perl make grep unzip gawk subversion libz-dev libc-dev rsync pip unzip libncurses5-dev libncursesw5-dev git swig
      - make dirclean
      - make clean
      - ./scripts/feeds update -a
      - ./scripts/feeds install -a
      - git restore .config
      - make -j2
      #- ./make-all.sh megafi -j10 -n
      #- ./make-all.sh -n -np fi -j10 -n
      #- ./make-all.sh -n -np ei -j10 -n
      #- ./scripts/static-checker.sh | tee ../ei-awc-openwrt/artifacts-nextivity/static-check.log
      # - command
      # - command
  post_build:
    commands:
       - echo "post_bild"
      # - command
#reports:
  #report-name-or-arn:
    #files:
      # - location
      # - location
    #base-directory: location
    #discard-paths: yes
    #file-format: JunitXml | CucumberJson
#artifacts:
 # files:
   
    # - location
  #name: $(date +%Y-%m-%d)
  #discard-paths: yes
 # base-directory: '../ei-awc-openwrt/artifacts-nextivity'
#cache:
  #paths:
    # - paths
