#!/bin/sh /etc/rc.common
# Copyright (C) 2021-2023 Nextivity Inc. https://nextivityinc.com/

USE_PROCD=1
START=81


get_board() {
  board=$(grep "Target board" /etc/nextivity_build_info 2>/dev/null | cut -d ' ' -f 3)
}


stop_service() {
  get_board

  if [ "$board" == "ei" ] ; then
    killall quectel-CM 2>/dev/null || true
    #rmmod qmi_wwan 2>/dev/null || true
  fi
}


service_triggers() {
  get_board

  # This is to check for swap between NAT and Passthrough mode. 
  procd_add_config_trigger "config.change" "awc" /sbin/awc-set-mode.sh -c
}


start_service() {
  get_board

  mkdir -p /tmp/nextivity

  config_load awc

  local enabled

  config_get bridge_mode "main" "bridge_mode" not-found

  # If a sysupgrade happened, the processes will be running again
  /sbin/awc-set-mode.sh -p

  if [ "$bridge_mode" == "1" -o "$bridge_mode" == "on" -o "$bridge_mode" == "mm" ] ; then

    echo "Nextivity: Starting Passthrough mode"

    echo "true" > /tmp/nextivity/bridge_mode

    procd_open_instance
    procd_set_param command /sbin/awc-mode-monitor.sh
    procd_set_param respawn "${respawn_threshold:-3600}" "${respawn_timeout:-5}" "${respawn_retry:-5}"
    procd_set_param pidfile "/tmp/nextivity/awc-bridge-mode.pid"
    procd_close_instance

  else
    echo "Nextivity: Starting NAT mode"

    echo "false" > /tmp/nextivity/bridge_mode

    procd_open_instance
    procd_set_param command /sbin/awc-mode-monitor.sh
    procd_set_param respawn "${respawn_threshold:-3600}" "${respawn_timeout:-5}" "${respawn_retry:-5}"
    procd_set_param pidfile "/tmp/nextivity/awc-nat-mode.pid"
    procd_close_instance

    # Don't need to do anything else.  Services already enabled
  fi
}
