#!/bin/sh /etc/rc.common
# Copyright (C) 2021-2023 Nextivity Inc. https://nextivityinc.com/

USE_PROCD=1
START=81

stop_service() {
    :
}


reload_service()
{
   stop
   start
}


service_triggers()
{
    procd_add_reload_trigger "awc_cloud" "awc_uuid"
}



start_service() {
    procd_open_instance
    procd_set_param command /sbin/cloud-check.sh
    procd_set_param respawn "${respawn_threshold:-3600}" "${respawn_timeout:-5}" "${respawn_retry:-5}"
    procd_set_param pidfile "/tmp/nextivity/cloud-check.pid"
    procd_close_instance
}


