#!/bin/sh /etc/rc.common
 
START=81
STOP=15
USE_PROCD=1
EXEC=/sbin/failover.sh

debug(){                          
    logger -t "START_FAILOVER" "$1"               
}  
 
start_service() {   

    debug "Start service"
 
    # commands to launch application

    procd_open_instance                   
    procd_set_param command "$EXEC"
    procd_set_param respawn 3600 5 0 # respawn if crash, with limits
    procd_set_param pidfile /var/run/start_failover.pid	
    procd_close_instance   
}                 
  
stop_service() {            
    debug "Stop service"    
}

