#!/bin/sh /etc/rc.common

USE_PROCD=1
START=81

stop_service() {
    :
}


reload_service()
{
   stop
   start
}

start_service() {
    procd_open_instance
    procd_set_param command /sbin/update_mac_addr.sh
    procd_set_param respawn "${respawn_threshold:-3600}" "${respawn_timeout:-5}" "${respawn_retry:-5}"
    procd_set_param pidfile "/tmp/nextivity/update_mac_addr.pid"
    procd_close_instance
}
