#
# Copyright (C) 2020 Jo-Philipp Wich <jo@mein.io>
# Copyright (C) 2021 Assured Wireless <peternaulls@assuredwireless.com>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Nextivity OpenWrt theme
LUCI_DEPENDS:=

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
